# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

def pods
  pod 'ExytePopupView', :path => '../'
end
 
target 'Example' do
  	platform :ios, '14.0'
    pods
end
 
target 'ExampleMac' do
  	platform :osx, '10.16'
    pods
end

target 'ExampleWatch WatchKit Extension' do
	platform :watchos, '7.0'
    pods
end
